### PR TITLE
Implement wsrt

### PR DESCRIPTION
**Pull request by maxstoll94**

### CODE REVIEW

**Review by jbikker — APPROVED** [review]

**Review by jbikker — COMMENTED** [review]
This has been addressed with a generic solution.

**Review by jbikker — APPROVED** [review]

**Review by jbikker — APPROVED** [review]

**Comment by jbikker** [comment]
Please fork the project and implement your wsrt in your own repo.

**Comment by maxstoll94** [comment]
Hi Mr. Bikker,

I am so sorry, I did do this, but accidentally created the pull request on
the wrong project. Won't happen again :)

With kind regards,

Max

**Comment by jbikker** [comment]
Not a problem, github is mostly new for me so I went through all the
buttons and interfaces. Pull requests look like a fun feature. ;)

**Pull request closed without merging**
